//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicioTarjetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        public int TAR_CODIGO { get; set; }
        public string TAR_NUMERO { get; set; }
        public string TAR_TIPO { get; set; }
        public Nullable<decimal> TAR_SALDO { get; set; }
        public Nullable<System.DateTime> TAR_FECHA_EMISION { get; set; }
        public Nullable<System.DateTime> TAR_FECHA_VENCIMIENTO { get; set; }
        public string TAR_ESTADO { get; set; }
        public Nullable<int> TAR_CODIGO_CLIENTE { get; set; }
        public string TAR_NOMBRE_CLIENTE { get; set; }
        public Nullable<int> EMI_CODIGO { get; set; }
    
        public virtual EMISOR EMISOR { get; set; }
    }
}
