//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionTarjetas.ServicioTarjetas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMISOR", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioTarjetas.Models")]
    [System.SerializableAttribute()]
    public partial class EMISOR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EMI_CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMI_DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EMI_NUMERO_DIGITOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMI_PREFIJOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMI_CODIGO {
            get {
                return this.EMI_CODIGOField;
            }
            set {
                if ((this.EMI_CODIGOField.Equals(value) != true)) {
                    this.EMI_CODIGOField = value;
                    this.RaisePropertyChanged("EMI_CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMI_DESCRIPCION {
            get {
                return this.EMI_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMI_DESCRIPCIONField, value) != true)) {
                    this.EMI_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("EMI_DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMI_NUMERO_DIGITOS {
            get {
                return this.EMI_NUMERO_DIGITOSField;
            }
            set {
                if ((this.EMI_NUMERO_DIGITOSField.Equals(value) != true)) {
                    this.EMI_NUMERO_DIGITOSField = value;
                    this.RaisePropertyChanged("EMI_NUMERO_DIGITOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMI_PREFIJO {
            get {
                return this.EMI_PREFIJOField;
            }
            set {
                if ((object.ReferenceEquals(this.EMI_PREFIJOField, value) != true)) {
                    this.EMI_PREFIJOField = value;
                    this.RaisePropertyChanged("EMI_PREFIJO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioTarjetas")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioTarjetas.IEmisor")]
    public interface IEmisor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ConsultarEmisores", ReplyAction="http://tempuri.org/IEmisor/ConsultarEmisoresResponse")]
        AplicacionTarjetas.ServicioTarjetas.EMISOR[] ConsultarEmisores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ConsultarEmisores", ReplyAction="http://tempuri.org/IEmisor/ConsultarEmisoresResponse")]
        System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.EMISOR[]> ConsultarEmisoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetData", ReplyAction="http://tempuri.org/IEmisor/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetData", ReplyAction="http://tempuri.org/IEmisor/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEmisor/GetDataUsingDataContractResponse")]
        AplicacionTarjetas.ServicioTarjetas.CompositeType GetDataUsingDataContract(AplicacionTarjetas.ServicioTarjetas.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEmisor/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.CompositeType> GetDataUsingDataContractAsync(AplicacionTarjetas.ServicioTarjetas.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmisorChannel : AplicacionTarjetas.ServicioTarjetas.IEmisor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmisorClient : System.ServiceModel.ClientBase<AplicacionTarjetas.ServicioTarjetas.IEmisor>, AplicacionTarjetas.ServicioTarjetas.IEmisor {
        
        public EmisorClient() {
        }
        
        public EmisorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmisorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmisorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmisorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionTarjetas.ServicioTarjetas.EMISOR[] ConsultarEmisores() {
            return base.Channel.ConsultarEmisores();
        }
        
        public System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.EMISOR[]> ConsultarEmisoresAsync() {
            return base.Channel.ConsultarEmisoresAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AplicacionTarjetas.ServicioTarjetas.CompositeType GetDataUsingDataContract(AplicacionTarjetas.ServicioTarjetas.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.CompositeType> GetDataUsingDataContractAsync(AplicacionTarjetas.ServicioTarjetas.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
